### ISSUE TITLE
Installation issue about SFBulkAPIStarter 0.12.0

### ISSUE THREAD

**Issue by danieleboldrini** [lfreeland/Salesforce-Bulk-API-Starter#4]
Hi, I'm trying to install SFBulkAPIStarter 0.12.0 on visual studio 2015 by nuget (NET framework 4.5.2)
but nuget shows the following error:

Could not install package 'SFBulkAPIStarter 0.12.0'. You are trying to install this package into a project that targets 
'.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework.

Instead, if I try to install "SFBulkAPIStarter 0.11.0", the installation process is performed correctly.
Can you help me?
Thanks a lot

**Comment by lfreeland** [comment]
I'm able to reproduce the issue in VisualStudio 2015 Community Edition. It seems like VisualStudio 2015 is having an issue because it's not targeting a specific .Net runtime version. I'll try uploading a new version with a designated .Net runtime version. I have VisualStudio 2013 installed and it's able to install it successfully in that version. In the meantime, try installing the Nuget package in VisualStudio 2013.

**Comment by lfreeland** [comment]
Version 0.13.0 has been uploaded to Nuget with a targeted runtime of .Net 4.5. I'm able to install that successfully in VisualStudio 2015 now.

If you have any other issues, please let me know.
